### ISSUE TITLE
The code breaks when the user bio doesn't have all three links

### ISSUE THREAD

**Issue by Syrux64** [Syrux64/alumni-portal#2]
# To recreate the issue
In '/profile/{username}' route, if the user doesn't have all the three links (LinkedIn, GitHub & E-Mail) the code breaks. 

# Proposed solution
Add proper exception handling regardless of the number of links user has added in their bio

**Comment by sandhig** [comment]
Hi! Can I take on this issue if no one is working on it currently?

**Comment by Syrux64** [comment]
Hey, @sandhig ! I appreciate your contribution. I'll assign this issue to you. Could you please start working on this ASAP? Feel free to clarify any doubts regarding our codebase ;)

**Comment by Syrux64** [comment]
The bug is fixed now. Appreciate your willingness to contribute, @sandhig !
